/*
  # Seed Exercises
  Populates the exercises table with the full classical Pilates exercise list
  from the Alisa client card, organized by apparatus.

  Only runs if the exercises table is empty (idempotent).
*/

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM exercises LIMIT 1) THEN
    RETURN; -- already seeded
  END IF;

  -- ─── REFORMER ──────────────────────────────────────────────────────────────
  INSERT INTO exercises (apparatus, name, springs, order_index) VALUES
    ('reformer', 'Footwork: Toes',              '4',     10),
    ('reformer', 'Footwork: Arches',            '4',     20),
    ('reformer', 'Footwork: Heels',             '2',     30),
    ('reformer', 'Footwork: Tendon Stretch',    '2',     40),
    ('reformer', 'The Hundred',                 '4',     50),
    ('reformer', 'Overhead',                    '2',     60),
    ('reformer', 'Coordination',                '2',     70),
    ('reformer', 'Rowing: Into the Sternum',    '1',     80),
    ('reformer', 'Rowing: 90°',                 '1',     90),
    ('reformer', 'Rowing: Chest',               '1',    100),
    ('reformer', 'Rowing: Hips',                '1',    110),
    ('reformer', 'Rowing: Shave',               '1',    120),
    ('reformer', 'Rowing: Hug',                 '1',    130),
    ('reformer', 'Swan on Barrel',              '2',    140),
    ('reformer', 'Long Box: Pull Straps I',     '1',    150),
    ('reformer', 'Long Box: Pull Straps II',    '1',    160),
    ('reformer', 'Backstroke',                  '1',    170),
    ('reformer', 'Swimming',                    '1',    180),
    ('reformer', 'Teaser',                      '2',    190),
    ('reformer', 'Breaststroke',                '2',    200),
    ('reformer', 'Horseback',                   '2',    210),
    ('reformer', 'Short Box: Round',            '2',    220),
    ('reformer', 'Short Box: Flat',             '2',    230),
    ('reformer', 'Short Box: Side to Side',     '2',    240),
    ('reformer', 'Short Box: Twist',            '2',    250),
    ('reformer', 'Short Box: Tree',             '2',    260),
    ('reformer', 'Long Stretch',                '4',    270),
    ('reformer', 'Down Stretch',                '3',    280),
    ('reformer', 'Up Stretch',                  '2',    290),
    ('reformer', 'Elephant',                    '2',    300),
    ('reformer', 'Arabesque I',                 '2',    310),
    ('reformer', 'Arabesque II',                '2',    320),
    ('reformer', 'Arabesque III',               '2',    330),
    ('reformer', 'Long Backstretch',            '3',    340),
    ('reformer', 'Stomach Massage: Round',      '2',    350),
    ('reformer', 'Stomach Massage: Hands Back', '2',    360),
    ('reformer', 'Stomach Massage: Reach Up',   '2',    370),
    ('reformer', 'Stomach Massage: Twist',      '2',    380),
    ('reformer', 'Tendon Stretch',              '1',    390),
    ('reformer', 'Tendon Stretch: 1 Leg Front', '1',    400),
    ('reformer', 'Tendon Stretch: 1 Leg Side',  '1',    410),
    ('reformer', 'Tendon Stretch: 1 Leg Back',  '1',    420),
    ('reformer', 'Short Spine Massage',         '1',    430),
    ('reformer', 'High Frog',                   '1',    440),
    ('reformer', 'Head Stand Front',            '1',    450),
    ('reformer', 'Head Stand Back',             '1',    460),
    ('reformer', 'Semi-Circle Bar Up',          '2',    470),
    ('reformer', 'Semi-Circle Bar Down',        '2',    480),
    ('reformer', 'Chest Expansion',             '2',    490),
    ('reformer', 'Thigh Stretch',               '2',    500),
    ('reformer', 'Backbend',                    '2',    510),
    ('reformer', 'Front Chest Expansion: Arm Circles', '1', 520),
    ('reformer', 'Front Chest Expansion: Shave',       '1', 530),
    ('reformer', 'Swakate',                     '2',    540),
    ('reformer', 'Hoopla',                      '2',    550),
    ('reformer', 'Profile',                     '2',    560),
    ('reformer', 'Lotus',                       '2',    570),
    ('reformer', 'Snake',                       '2',    580),
    ('reformer', 'Twist',                       '2',    590),
    ('reformer', 'Twist w/ Bar Up',             '2',    600),
    ('reformer', 'Bridge',                      '2',    610),
    ('reformer', 'Corkscrew',                   '2',    620),
    ('reformer', 'Step-off Control Balance',    '2',    630),
    ('reformer', '2nd Long Box: Rocking',       '4',    640),
    ('reformer', '2nd Long Box: Grasshopper',   '4',    650),
    ('reformer', '2nd Long Box: Swan',          '4',    660),
    ('reformer', 'Mermaid',                     '4',    670),
    ('reformer', 'Longspine',                   '2',    680),
    ('reformer', 'Leg Circles',                 '2',    690),
    ('reformer', 'Frog',                        '2',    700),
    ('reformer', 'Knee Stretches: Round',       '2',    710),
    ('reformer', 'Knee Stretches: Arched',      '2',    720),
    ('reformer', 'Knee Stretches: Knees Off',   '2',    730),
    ('reformer', 'Knee Stretches: 1 Leg',       '2',    740),
    ('reformer', 'Knee Stretches: Alternate Legs','2',  750),
    ('reformer', 'Running',                     '1',    760),
    ('reformer', 'Pelvic Lift',                 '2',    770),
    ('reformer', 'Pelvic Lift: 1st Position',   '2',    780),
    ('reformer', 'Push Up Front',               '1',    790),
    ('reformer', 'Push Up Back',                '2',    800),
    ('reformer', 'Star',                        '2',    810),
    ('reformer', 'Side Split',                  '2',    820),
    ('reformer', 'Front Split',                 '2',    830),
    ('reformer', 'Russian Split',               '2',    840),
    ('reformer', 'Jumping Board',               NULL,   850);

  -- ─── MAT ───────────────────────────────────────────────────────────────────
  INSERT INTO exercises (apparatus, name, springs, order_index) VALUES
    ('mat', 'Hundred',                          NULL,   10),
    ('mat', 'Roll-Up',                          NULL,   20),
    ('mat', 'Roll-Over with Legs Spread',       NULL,   30),
    ('mat', 'Single Leg Circles',               NULL,   40),
    ('mat', 'Rolling Like a Ball',              NULL,   50),
    ('mat', 'Single Leg Stretch',               NULL,   60),
    ('mat', 'Double Leg Stretch',               NULL,   70),
    ('mat', 'Single Straight Leg Stretch',      NULL,   80),
    ('mat', 'Double Straight Leg Stretch',      NULL,   90),
    ('mat', 'Criss-Cross',                      NULL,  100),
    ('mat', 'Spine Stretch Forward',            NULL,  110),
    ('mat', 'Open Leg Rocker',                  NULL,  120),
    ('mat', 'Corkscrew',                        NULL,  130),
    ('mat', 'Saw',                              NULL,  140),
    ('mat', 'Swan Dive',                        NULL,  150),
    ('mat', 'Neck Roll',                        NULL,  160),
    ('mat', 'Single Leg Kicks',                 NULL,  170),
    ('mat', 'Double Leg Kicks',                 NULL,  180),
    ('mat', 'Neck Pull',                        NULL,  190),
    ('mat', 'Scissors',                         NULL,  200),
    ('mat', 'Bicycle',                          NULL,  210),
    ('mat', 'Shoulder Bridge',                  NULL,  220),
    ('mat', 'Spine Twist',                      NULL,  230),
    ('mat', 'Jackknife',                        NULL,  240),
    ('mat', 'Side Kicks: Up Down',              NULL,  250),
    ('mat', 'Side Kicks: Small Circles',        NULL,  260),
    ('mat', 'Side Kicks: Bicycle',              NULL,  270),
    ('mat', 'Leg Lifts',                        NULL,  280),
    ('mat', 'Leg Beats',                        NULL,  290),
    ('mat', 'Circling Inner Thigh',             NULL,  300),
    ('mat', 'Hot Potato',                       NULL,  310),
    ('mat', 'Big Scissors',                     NULL,  320),
    ('mat', 'Grand Ronde de Jambe',             NULL,  330),
    ('mat', 'Shaking Legs',                     NULL,  340),
    ('mat', 'Teaser 1',                         NULL,  350),
    ('mat', 'Teaser 2',                         NULL,  360),
    ('mat', 'Teaser 3',                         NULL,  370),
    ('mat', 'Hip Circles',                      NULL,  380),
    ('mat', 'Can-Can',                          NULL,  390),
    ('mat', 'Swimming',                         NULL,  400),
    ('mat', 'Leg Pull Down',                    NULL,  410),
    ('mat', 'Leg Pull Up',                      NULL,  420),
    ('mat', 'Kneeling Side Kicks',              NULL,  430),
    ('mat', 'Mermaid',                          NULL,  440),
    ('mat', 'Boomerang',                        NULL,  450),
    ('mat', 'Seal',                             NULL,  460),
    ('mat', 'Push Ups',                         NULL,  470),
    ('mat', 'Crab',                             NULL,  480),
    ('mat', 'Rocking',                          NULL,  490),
    ('mat', 'Control Balance',                  NULL,  500);

  -- ─── MAGIC CIRCLE ──────────────────────────────────────────────────────────
  INSERT INTO exercises (apparatus, name, springs, order_index) VALUES
    ('magic_circle', 'On Mat: Hundred (hands)',          NULL,  10),
    ('magic_circle', 'On Mat: Hundred (ankles)',         NULL,  20),
    ('magic_circle', 'On Mat: Roll Up (hands)',          NULL,  30),
    ('magic_circle', 'On Mat: Roll Over (ankles)',       NULL,  40),
    ('magic_circle', 'On Mat: Double Leg Stretch (ankles)', NULL, 50),
    ('magic_circle', 'On Mat: Double Straight Leg (ankles)',NULL, 60),
    ('magic_circle', 'On Mat: Open Leg Rocker (ankles)', NULL,  70),
    ('magic_circle', 'On Mat: Corkscrew (ankles)',       NULL,  80),
    ('magic_circle', 'On Mat: Neck Pull (ankles)',       NULL,  90),
    ('magic_circle', 'On Mat: Jackknife (ankles)',       NULL, 100),
    ('magic_circle', 'On Mat: Side Kick — Top Leg Press Down', NULL, 110),
    ('magic_circle', 'On Mat: Side Kick — Top Leg Press Up',   NULL, 120),
    ('magic_circle', 'On Mat: Side Kick — On Stomach Squeeze', NULL, 130),
    ('magic_circle', 'On Mat: Teaser',                   NULL, 140),
    ('magic_circle', 'On Mat: Hip Circles (ankles)',     NULL, 150),
    ('magic_circle', 'Sitting: Knees (feet together)',   NULL, 160),
    ('magic_circle', 'Sitting: Knees (soles)',           NULL, 170),
    ('magic_circle', 'Sitting: Knees (flat, squeeze & grow)', NULL, 180),
    ('magic_circle', 'Sitting: Feet',                    NULL, 190),
    ('magic_circle', 'Standing Arms: Pumping — Sternum', NULL, 200),
    ('magic_circle', 'Standing Arms: Pumping — Hips',    NULL, 210),
    ('magic_circle', 'Standing Arms: Pumping — Ears',    NULL, 220),
    ('magic_circle', 'Standing Arms: 10x Up-Down',       NULL, 230),
    ('magic_circle', 'Standing Arms: Back',              NULL, 240),
    ('magic_circle', 'Standing Arms: Sides',             NULL, 250),
    ('magic_circle', 'Standing Legs: Sideways (ankles)', NULL, 260),
    ('magic_circle', 'Standing Legs: 3rd Position',      NULL, 270),
    ('magic_circle', 'Standing Legs: On Demi-Pointe',    NULL, 280);

  -- ─── CADILLAC ──────────────────────────────────────────────────────────────
  INSERT INTO exercises (apparatus, name, springs, order_index) VALUES
    ('cadillac', 'Rolling Back',                         NULL,  10),
    ('cadillac', 'Rolling Back: One Arm',                NULL,  20),
    ('cadillac', 'Leg Spring: Circles',                  NULL,  30),
    ('cadillac', 'Leg Spring: Walking',                  NULL,  40),
    ('cadillac', 'Leg Spring: Beats',                    NULL,  50),
    ('cadillac', 'Leg Spring: Ronde de Jambe',           NULL,  60),
    ('cadillac', 'Leg Spring: Bicycle',                  NULL,  70),
    ('cadillac', 'Leg Spring: Frog',                     NULL,  80),
    ('cadillac', 'Leg Spring: Frog in the Air',          NULL,  90),
    ('cadillac', 'Airplane',                             NULL, 100),
    ('cadillac', 'Arm Spring: Circles',                  NULL, 110),
    ('cadillac', 'Arm Spring: Triceps',                  NULL, 120),
    ('cadillac', 'Arm Spring: Flying Eagle',             NULL, 130),
    ('cadillac', 'Side Leg Spring: Front-Back',          NULL, 140),
    ('cadillac', 'Side Leg Spring: Up-Down',             NULL, 150),
    ('cadillac', 'Side Leg Spring: Small Circles',       NULL, 160),
    ('cadillac', 'Side Leg Spring: Bicycle',             NULL, 170),
    ('cadillac', 'Tower',                                NULL, 180),
    ('cadillac', 'Monkey',                               NULL, 190),
    ('cadillac', 'Hip Stretch',                          NULL, 200),
    ('cadillac', 'Push Through',                         NULL, 210),
    ('cadillac', 'Reverse Push Through',                 NULL, 220),
    ('cadillac', 'Push Through: Teaser',                 NULL, 230),
    ('cadillac', 'Push Through: Press Down',             NULL, 240),
    ('cadillac', 'Push Through: Shoulder Roll Down',     NULL, 250),
    ('cadillac', 'Chest Expansion',                      NULL, 260),
    ('cadillac', 'Thigh Stretch',                        NULL, 270),
    ('cadillac', 'Long Back Stretch Arms',               NULL, 280),
    ('cadillac', 'Standing Arm Springs: Squats',         NULL, 290),
    ('cadillac', 'Standing Arm Springs: Boxing',         NULL, 300),
    ('cadillac', 'Standing Arm Springs: Shave',          NULL, 310),
    ('cadillac', 'Standing Arm Springs: Hug',            NULL, 320),
    ('cadillac', 'Standing Arm Springs: Butterfly',      NULL, 330),
    ('cadillac', 'Standing Arm Springs: Side Arm',       NULL, 340),
    ('cadillac', 'Standing Arm Springs: Fencing',        NULL, 350),
    ('cadillac', 'Standing w/ Rollback Bar: Chest Expansion', NULL, 360),
    ('cadillac', 'Standing w/ Rollback Bar: Side Arm',   NULL, 370),
    ('cadillac', 'Standing w/ Rollback Bar: Shaving',    NULL, 380),
    ('cadillac', 'Rolling In & Out',                     NULL, 390),
    ('cadillac', 'Rolling Stomach Massage',              NULL, 400),
    ('cadillac', 'Ending: Breathing',                    NULL, 410),
    ('cadillac', 'Ending: Spread Eagle',                 NULL, 420),
    ('cadillac', 'Ending: Pull Ups',                     NULL, 430),
    ('cadillac', 'Ending: Hanging Pull Ups',             NULL, 440),
    ('cadillac', 'Half Hanging',                         NULL, 450),
    ('cadillac', 'Hanging',                              NULL, 460);

  -- ─── BIG CHAIR (High Chair) ────────────────────────────────────────────────
  INSERT INTO exercises (apparatus, name, springs, order_index) VALUES
    ('big_chair', 'Pumping',                             NULL,  10),
    ('big_chair', 'Pumping: One Leg',                    NULL,  20),
    ('big_chair', 'Parallel Pumping',                    NULL,  30),
    ('big_chair', 'Going Up Front',                      NULL,  40),
    ('big_chair', 'Going Up Side',                       NULL,  50),
    ('big_chair', 'Pump One Leg: Demi-Pointe',           NULL,  60),
    ('big_chair', 'Pump One Leg: Front',                 NULL,  70),
    ('big_chair', 'Pump One Leg: Side',                  NULL,  80),
    ('big_chair', 'Pump One Leg: Crossover',             NULL,  90),
    ('big_chair', 'Achilles Stretch',                    NULL, 100),
    ('big_chair', 'Press Up: Bottom',                    NULL, 110),
    ('big_chair', 'Press Up: Front',                     NULL, 120);

  -- ─── WUNDA CHAIR ───────────────────────────────────────────────────────────
  INSERT INTO exercises (apparatus, name, springs, order_index) VALUES
    ('wunda_chair', 'Footwork: Toes',                    NULL,  10),
    ('wunda_chair', 'Footwork: Arches',                  NULL,  20),
    ('wunda_chair', 'Footwork: Heels',                   NULL,  30),
    ('wunda_chair', 'Footwork: Tendon Stretch',          NULL,  40),
    ('wunda_chair', 'Push Down',                         NULL,  50),
    ('wunda_chair', 'Swan Dive',                         NULL,  60),
    ('wunda_chair', 'Pumping One Arm',                   NULL,  70),
    ('wunda_chair', 'Teaser',                            NULL,  80),
    ('wunda_chair', 'Mermaid',                           NULL,  90),
    ('wunda_chair', 'Backward Arms',                     NULL, 100),
    ('wunda_chair', 'Arm Frog',                          NULL, 110),
    ('wunda_chair', 'Mermaid Kneeling',                  NULL, 120),
    ('wunda_chair', 'Horseback',                         NULL, 130),
    ('wunda_chair', 'Push Up Sideways 1 (bottom arm bends)', NULL, 140),
    ('wunda_chair', 'Twist 1',                           NULL, 150),
    ('wunda_chair', 'Push Up Sideways 2 (top arm bends)',NULL, 160),
    ('wunda_chair', 'Tendon Stretch',                    NULL, 170),
    ('wunda_chair', 'Tendon Stretch: 1 Leg',             NULL, 180),
    ('wunda_chair', 'Mountain Climb',                    NULL, 190),
    ('wunda_chair', 'Pull Up',                           NULL, 200),
    ('wunda_chair', 'Table',                             NULL, 210),
    ('wunda_chair', 'Pull Up: 1 Arm',                    NULL, 220),
    ('wunda_chair', 'Flying Eagle',                      NULL, 230),
    ('wunda_chair', 'Front Balance Control',             NULL, 240),
    ('wunda_chair', 'Side Balance Control',              NULL, 250),
    ('wunda_chair', 'Corkscrew',                         NULL, 260),
    ('wunda_chair', 'Push Down: 1 Arm (sideways)',       NULL, 270),
    ('wunda_chair', 'Frog: Facing Chair',                NULL, 280),
    ('wunda_chair', 'Spine Stretch',                     NULL, 290),
    ('wunda_chair', 'Stretch / Press Down Teaser',       NULL, 300),
    ('wunda_chair', 'Frog Facing Out',                   NULL, 310),
    ('wunda_chair', 'Pumping Standing',                  NULL, 320),
    ('wunda_chair', 'Pumping on Knees',                  NULL, 330),
    ('wunda_chair', 'Leg Push Down: Front',              NULL, 340),
    ('wunda_chair', 'Leg Push Down: Side',               NULL, 350),
    ('wunda_chair', 'Leg Push Down: Back',               NULL, 360),
    ('wunda_chair', 'Push Up (toes on pedal)',           NULL, 370),
    ('wunda_chair', 'Star',                              NULL, 380);

  -- ─── SMALL BARREL / SPINE CORRECTOR ────────────────────────────────────────
  INSERT INTO exercises (apparatus, name, springs, order_index) VALUES
    ('small_barrel', 'Leg Series: Circles',              NULL,  10),
    ('small_barrel', 'Leg Series: Scissors',             NULL,  20),
    ('small_barrel', 'Leg Series: Walking',              NULL,  30),
    ('small_barrel', 'Leg Series: Bicycle',              NULL,  40),
    ('small_barrel', 'Leg Series: Beats',                NULL,  50),
    ('small_barrel', 'Leg Series: Roll In and Out',      NULL,  60),
    ('small_barrel', 'Leg Series: Rest',                 NULL,  70),
    ('small_barrel', 'Arm Stretch with Bar',             NULL,  80),
    ('small_barrel', 'Arm Circles',                      NULL,  90),
    ('small_barrel', 'Leg Circles onto Head',            NULL, 100),
    ('small_barrel', 'Teaser',                           NULL, 110),
    ('small_barrel', 'Hip Circles',                      NULL, 120),
    ('small_barrel', 'Swan',                             NULL, 130),
    ('small_barrel', 'Grasshopper',                      NULL, 140),
    ('small_barrel', 'Rocking',                          NULL, 150),
    ('small_barrel', 'Swimming',                         NULL, 160),
    ('small_barrel', 'Side Sit Ups',                     NULL, 170),
    ('small_barrel', 'Shoulder Bridge',                  NULL, 180);

  -- ─── ARM WEIGHTS ───────────────────────────────────────────────────────────
  INSERT INTO exercises (apparatus, name, springs, order_index) VALUES
    ('arm_weights', '90 Degrees: Forward',               NULL,  10),
    ('arm_weights', '90 Degrees: Side',                  NULL,  20),
    ('arm_weights', '90 Degrees: Curls from Waist',      NULL,  30),
    ('arm_weights', 'Boxing (tabletop)',                  NULL,  40),
    ('arm_weights', 'Sides (roll up to Pilates stance)',  NULL,  50),
    ('arm_weights', 'The Bug (tabletop)',                 NULL,  60),
    ('arm_weights', 'Zip Up (roll up to Pilates stance)', NULL,  70),
    ('arm_weights', 'Shaving',                           NULL,  80),
    ('arm_weights', 'Low Curls (tabletop)',               NULL,  90),
    ('arm_weights', 'Chest Expansion (Pilates stance)',   NULL, 100),
    ('arm_weights', 'Arm Circles (small going up)',       NULL, 110),
    ('arm_weights', 'Lunges',                            NULL, 120),
    ('arm_weights', 'Wall: Arm Circles',                 NULL, 130),
    ('arm_weights', 'Wall: Peel Down',                   NULL, 140),
    ('arm_weights', 'Wall: Squats',                      NULL, 150);

  -- ─── PED-O-PUL ─────────────────────────────────────────────────────────────
  INSERT INTO exercises (apparatus, name, springs, order_index) VALUES
    ('ped_o_pul', 'Chest Expansion',                     NULL,  10),
    ('ped_o_pul', 'Arm Circles',                         NULL,  20),
    ('ped_o_pul', 'Knee Bends (demi-pointe, plié)',      NULL,  30),
    ('ped_o_pul', 'Arm Circles + Knee Bends',            NULL,  40),
    ('ped_o_pul', 'Centering',                           NULL,  50),
    ('ped_o_pul', 'Knee Bends: 1 Leg — Front Attitude',  NULL,  60),
    ('ped_o_pul', 'Knee Bends: 1 Leg — Side Attitude',   NULL,  70),
    ('ped_o_pul', 'Knee Bends: 1 Leg — Low Arabesque',   NULL,  80);

  -- ─── LARGE BARREL ──────────────────────────────────────────────────────────
  INSERT INTO exercises (apparatus, name, springs, order_index) VALUES
    ('large_barrel', 'Swan Dive',                        NULL,  10),
    ('large_barrel', 'Horseback',                        NULL,  20),
    ('large_barrel', 'Short Box: Round',                 NULL,  30),
    ('large_barrel', 'Short Box: Flat',                  NULL,  40),
    ('large_barrel', 'Short Box: Side',                  NULL,  50),
    ('large_barrel', 'Short Box: Twist',                 NULL,  60),
    ('large_barrel', 'Side Sit Up',                      NULL,  70),
    ('large_barrel', 'Side Sit Up: One Leg',             NULL,  80),
    ('large_barrel', 'Ballet Stretch: Front',            NULL,  90),
    ('large_barrel', 'Ballet Stretch: Front w/ Bent Leg',NULL, 100),
    ('large_barrel', 'Ballet Stretch: Side',             NULL, 110),
    ('large_barrel', 'Ballet Stretch: Side w/ Bent Leg', NULL, 120),
    ('large_barrel', 'Ballet Stretch: Back',             NULL, 130),
    ('large_barrel', 'Backward Stretch',                 NULL, 140),
    ('large_barrel', 'Backward Stretch Hanging',         NULL, 150),
    ('large_barrel', 'Handstand',                        NULL, 160),
    ('large_barrel', 'Jumping Off the Stomach',          NULL, 170);

END $$;
